# Generated by Django 2.0.3 on 2018-04-23 01:16

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='full_url',
            field=django.contrib.postgres.fields.citext.CITextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='hostname',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='param_hash_key',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='param_key',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='url',
            field=django.contrib.postgres.fields.citext.CITextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='url_key',
            field=models.TextField(null=True),
        ),
    ]
