# Generated by Django 2.0.3 on 2018-04-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machina', '0002_auto_20180423_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='res_code',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
