# Generated by Django 2.0.3 on 2018-03-19 04:24

import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import HStoreExtension, CITextExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        CITextExtension(),
        migrations.CreateModel(
            name='DictModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_param', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(default='')),
                ('trace', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('client', models.GenericIPAddressField()),
                ('hostname', models.TextField(default='')),
                ('machine', models.TextField()),
                ('language', models.TextField(choices=[('CSHARP', 'CSharp'), ('PY2', 'Python2'), ('PY3', 'Python3'), ('CPP', 'C++'), ('C', 'C'), ('JS', 'Javascript'), ('PSH', 'Powershell')], default='CSHARP')),
            ],
        ),
        migrations.CreateModel(
            name='PKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', django.contrib.postgres.fields.citext.CITextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvals', to='machina.PKey')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modfied', models.DateTimeField(auto_now=True)),
                ('req_header', django.contrib.postgres.fields.hstore.HStoreField()),
                ('method', models.TextField(default='')),
                ('full_url', django.contrib.postgres.fields.citext.CITextField(max_length=2000)),
                ('url', django.contrib.postgres.fields.citext.CITextField(max_length=2000)),
                ('url_param', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('body_param', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('client_ip', models.GenericIPAddressField(null=True)),
                ('client_port', models.IntegerField(blank=True, null=True)),
                ('client_process', django.contrib.postgres.fields.citext.CITextField(blank=True, null=True)),
                ('server_ip', models.GenericIPAddressField(null=True)),
                ('server_port', models.IntegerField(blank=True, null=True)),
                ('res_header', django.contrib.postgres.fields.hstore.HStoreField()),
                ('comment', models.TextField(blank=True, default='')),
                ('is_https', models.BooleanField(default=False)),
                ('has_body', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
