# Generated by Django 2.0.3 on 2018-03-31 18:44

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='hostname',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=2000),
        ),
    ]
