# Generated by Django 2.0.3 on 2018-03-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machina', '0002_test_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_url', models.TextField()),
                ('p_hash', models.TextField(unique=True)),
                ('p_value', models.TextField()),
            ],
        ),
    ]
