# Generated by Django 2.0.3 on 2018-04-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machina', '0003_uniqueurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='param_hash_key',
            field=models.TextField(max_length=2000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='test',
            name='param_key',
            field=models.TextField(max_length=2000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='test',
            name='url_key',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
